/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdcc6",
        "on-secondary-fixed": "#001f26",
        "inverse-on-surface": "#2e3038",
        "on-primary-container": "#00285d",
        "on-primary-fixed-variant": "#004395",
        "error": "#ffb4ab",
        "on-surface": "#e1e2ec",
        "tertiary": "#ffb786",
        "primary-container": "#4d8eff",
        "surface-container": "#1d2027",
        "primary-fixed-dim": "#adc6ff",
        "surface-container-lowest": "#0b0e15",
        "outline": "#8c909f",
        "on-tertiary-container": "#461f00",
        "on-background": "#e1e2ec",
        "on-tertiary-fixed-variant": "#723600",
        "on-secondary-container": "#00424e",
        "tertiary-fixed-dim": "#ffb786",
        "on-tertiary-fixed": "#311400",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#005ac2",
        "surface-container-high": "#272a31",
        "background": "#10131a",
        "on-primary": "#002e6a",
        "secondary-container": "#03b5d3",
        "inverse-surface": "#e1e2ec",
        "secondary-fixed-dim": "#4cd7f6",
        "surface-container-low": "#191b23",
        "error-container": "#93000a",
        "surface-dim": "#10131a",
        "on-secondary": "#003640",
        "surface-tint": "#adc6ff",
        "on-primary-fixed": "#001a42",
        "surface": "#10131a",
        "secondary-fixed": "#acedff",
        "on-error": "#690005",
        "surface-variant": "#32353c",
        "outline-variant": "#424754",
        "on-tertiary": "#502400",
        "surface-container-highest": "#32353c",
        "surface-bright": "#363941",
        "primary-fixed": "#d8e2ff",
        "on-surface-variant": "#c2c6d6",
        "on-secondary-fixed-variant": "#004e5c",
        "tertiary-container": "#df7412",
        "primary": "#adc6ff",
        "secondary": "#4cd7f6"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "gutter": "24px",
        "margin": "32px",
        "card-padding": "20px",
        "stack-gap": "12px"
      },
      fontFamily: {
        "header-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
        "display-xl": ["Inter", "sans-serif"],
        "data-mono": ["Inter", "monospace"]
      },
      fontSize: {
        "header-md": ["20px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "600"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "letterSpacing": "0", "fontWeight": "400"}],
        "display-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-base": ["16px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "display-xl": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "data-mono": ["14px", {"lineHeight": "1", "letterSpacing": "-0.01em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
