/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "var(--color-background)",
        "on-background": "var(--color-on-background)",
        "surface": "var(--color-surface)",
        "on-surface": "var(--color-on-surface)",
        "surface-variant": "var(--color-surface-variant)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-tint": "var(--color-surface-tint)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-dim": "var(--color-surface-dim)",
        "primary": "var(--color-primary)",
        "on-primary": "var(--color-on-primary)",
        "primary-container": "var(--color-primary-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "inverse-primary": "var(--color-inverse-primary)",
        "secondary": "var(--color-secondary)",
        "on-secondary": "var(--color-on-secondary)",
        "secondary-container": "var(--color-secondary-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "tertiary": "var(--color-tertiary)",
        "on-tertiary": "var(--color-on-tertiary)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "error": "var(--color-error)",
        "on-error": "var(--color-on-error)",
        "error-container": "var(--color-error-container)",
        "on-error-container": "var(--color-on-error-container)",
        "outline": "var(--color-outline)",
        "outline-variant": "var(--color-outline-variant)",
        "inverse-surface": "var(--color-inverse-surface)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "muted": "var(--color-muted)",
        "muted-soft": "var(--color-muted-soft)",
        "hairline": "var(--color-hairline)",
        "hairline-soft": "var(--color-hairline-soft)"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "gutter": "24px",
        "margin": "32px",
        "card-padding": "20px",
        "stack-gap": "12px"
      },
      fontFamily: {
        "serif": ["Copernicus", "Tiempos Headline", "Garamond", "Times New Roman", "serif"],
        "sans": ["StyreneB", "Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
        "mono": ["JetBrains Mono", "ui-monospace", "monospace"],
        "header-md": ["StyreneB", "Inter", "sans-serif"],
        "body-sm": ["StyreneB", "Inter", "sans-serif"],
        "display-lg": ["Copernicus", "Tiempos Headline", "Garamond", "Times New Roman", "serif"],
        "label-caps": ["StyreneB", "Inter", "sans-serif"],
        "body-base": ["StyreneB", "Inter", "sans-serif"],
        "display-xl": ["Copernicus", "Tiempos Headline", "Garamond", "Times New Roman", "serif"],
        "display-md": ["Copernicus", "Tiempos Headline", "Garamond", "Times New Roman", "serif"],
        "display-sm": ["Copernicus", "Tiempos Headline", "Garamond", "Times New Roman", "serif"],
        "data-mono": ["JetBrains Mono", "ui-monospace", "monospace"]
      },
      fontSize: {
        "header-md": ["18px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "500"}],
        "body-sm": ["14px", {"lineHeight": "1.55", "letterSpacing": "0", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-1px", "fontWeight": "400"}],
        "label-caps": ["12px", {"lineHeight": "1.4", "letterSpacing": "1.5px", "fontWeight": "500"}],
        "body-base": ["16px", {"lineHeight": "1.55", "letterSpacing": "0", "fontWeight": "400"}],
        "display-xl": ["64px", {"lineHeight": "1.05", "letterSpacing": "-1.5px", "fontWeight": "400"}],
        "display-md": ["36px", {"lineHeight": "1.15", "letterSpacing": "-0.5px", "fontWeight": "400"}],
        "display-sm": ["28px", {"lineHeight": "1.2", "letterSpacing": "-0.3px", "fontWeight": "400"}],
        "title-lg": ["22px", {"lineHeight": "1.3", "letterSpacing": "0", "fontWeight": "500"}],
        "title-md": ["18px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "500"}],
        "title-sm": ["16px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "500"}],
        "data-mono": ["14px", {"lineHeight": "1.6", "letterSpacing": "0", "fontWeight": "400"}],
        "button": ["14px", {"lineHeight": "1.0", "letterSpacing": "0", "fontWeight": "500"}],
        "nav-link": ["14px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "500"}],
        "caption": ["13px", {"lineHeight": "1.4", "letterSpacing": "0", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
